---
- name: Refresh token and update env
  import_playbook: egi_refresh_token.yml
  when: env.checkin_env is defined

- hosts: all
  gather_facts: no

  tasks:
    - set_fact:
        os_env: "{{ env.os_env }}"
      when: env.os_env is defined  

    - name: Create security group
      os_security_group:  
        name: "{{ group_name }}"
        state: present
        description: "{{ group_description }}"
      environment: "{{ os_env if os_env is defined }}"

    - name: Add security rules 
      os_security_group_rule:
        security_group: "{{ group_name }}"
        protocol: "{{ item.value.protocol }}"
        port_range_min: "{{ item.value.port_range_min }}"
        port_range_max: "{{ item.value.port_range_max }}"
        remote_ip_prefix: "{{ item.value.remote_ip_prefix }}"
        direction: "{{ item.value.direction if item.value.direction is defined else 'ingress' }}"
      loop: "{{ ports | dict2items }}"
      environment: "{{ os_env if os_env is defined }}"